// Copyright 2014-2018 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.


extern crate clap;
extern crate clippy_dev;
extern crate regex;

use clap::{App, Arg, SubCommand};
use clippy_dev::*;

fn main() {
    let matches = App::new("Clippy developer tooling")
        .subcommand(
            SubCommand::with_name("update_lints")
                .about("Update the lint list")
                .arg(
                    Arg::with_name("print-only")
                        .long("print-only")
                        .short("p")
                        .help("Print a table of lints to STDOUT. Does not modify any files."))
                .arg(
                    Arg::with_name("changes")
                        .short("c")
                        .help("Print a warning and set exit status to 1 if files would be changed"),
                ),
        )
        .get_matches();

    if let Some(matches) = matches.subcommand_matches("update_lints") {
        if matches.is_present("print-only") {
            print_lints();
        } else {
            update_lints();
        }
    }
}

fn print_lints() {
    let lint_list = gather_all();
    let usable_lints: Vec<Lint> = Lint::usable_lints(lint_list).collect();
    let lint_count = usable_lints.len();
    let grouped_by_lint_group = Lint::by_lint_group(&usable_lints);

    for (lint_group, mut lints) in grouped_by_lint_group {
        if lint_group == "Deprecated" { continue; }
        println!("\n## {}", lint_group);

        lints.sort_by_key(|l| l.name.clone());

        for lint in lints {
            println!("* [{}]({}#{}) ({})", lint.name, clippy_dev::DOCS_LINK.clone(), lint.name, lint.desc);
        }
    }

    println!("there are {} lints", lint_count);
}

fn update_lints() {
    let lint_list = gather_all();
    let usable_lints: Vec<Lint> = Lint::usable_lints(lint_list).collect();
    let lint_count = usable_lints.len();
    let clippy_version = clippy_version_from_toml();

    replace_region_in_file(
        "../README.md",
        r#"\[There are \d+ lints included in this crate!\]\(https://rust-lang-nursery.github.io/rust-clippy/master/index.html\)"#,
        "",
        true,
        || {
            vec![
                format!("[There are {} lints included in this crate!](https://rust-lang-nursery.github.io/rust-clippy/master/index.html)", lint_count)
            ]
        }
    );
    replace_region_in_file(
        "../CHANGELOG.md",
        "<!-- begin autogenerated links to lint list -->",
        "<!-- end autogenerated links to lint list -->",
        false,
        || {
            let mut lint_list_sorted = usable_lints.clone();
            lint_list_sorted.sort_by_key(|l| l.name.clone());
            lint_list_sorted
                .iter()
                .map(|l| {
                    format!("[`{}`]: {}#{}", l.name, clippy_dev::DOCS_LINK.clone(), l.name)
                })
                .collect()
        }
    );
    replace_region_in_file(
        "../Cargo.toml",
        "# begin automatic update",
        "# end automatic update",
        false,
        || {
            vec![
                format!("clippy_lints = {{ version = \"{}\", path = \"clippy_lints\" }}", clippy_version)
            ]
        }
    );
    replace_region_in_file(
        "../clippy_lints/Cargo.toml",
        "# begin automatic update",
        "# end automatic update",
        false,
        || {
            vec![format!("version = \"{}\"", clippy_version)]
        }
    );
    replace_region_in_file(
        "../clippy_lints/src/lib.rs",
        "begin lints modules",
        "end lints modules",
        false,
        || {
            let mut user_facing_lints_sorted = user_facing_lints.clone();
            user_facing_lints_sorted.sort_by_key(|l| l.name.clone());
            // TODO: This still includes incorrect modules
            Lint::gen_pub_mod_for_group(&user_facing_lints_sorted[..])
        }
    );
    // replace_region_in_file(
    //     "../clippy_lints/src/lib.rs",
    //     r#"reg.register_lint_group\("clippy""#,
    //     r#"\]\);"#,
    //     false,
    //     || {
    //         vec![
    //             // TODO: gen_group
    //         ]
    //     }
    // );
    // TODO: Add the register_lint_group inside the loop, too
}
